# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1061680f3bd225cf78916ed61e2fa08b3e5939ace5c6e38f76e139bec3f25fd420acba1b381d4aeab64e8befa253e9f81f2fb42f7e562b962f3f46eb565ef166

test:
  secret_key_base: 71bfa761e56e426277b521f84f26810abd56bc5ed8be26dfc2738d04e9a5cc11412077ba1e92fa5053e3b71668bf114fe3df0732fa523a4e525be2687dcc23ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
